name: Update GitHub Stats SVGs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/github-contrib-*.svg'
      - 'assets/github-activity-*.svg'
  schedule:
    - cron: "0 */3 * * *"   # Tự động cập nhật mỗi 3 tiếng

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate SVGs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python js/build_github_contrib_svgs.py tranhohoangvu assets

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-contrib-*.svg assets/github-activity-*.svg
          git diff --cached --quiet || (git commit -m "chore: update github stats svgs" && git push)
